SuperHeroProject/Controllers/SuperheroesController.cs
using SuperHeroProject.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using System.Data.Entity;
using System.Web;
using System.Web.Mvc;
using System.Net;

namespace SuperHeroProject.Controllers
{
    public class SuperheroesController : Controller
    {
        private ApplicationDbContext db = new ApplicationDbContext();
        // GET: Superheroes
        public ViewResult Index()
        {
            return View(db.superheroes.ToList());
        }
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Superhero superhero = db.superheroes.Find(id);
            if (superhero == null)
            {
                return HttpNotFound();
            }
            return View(superhero);
        }
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "SuperHeroName, AlterEgoName, PrimaryAbility, SecondaryAbility, CatchPhrase")]Superhero superhero)
        {
            try
            {
                if (ModelState.IsValid)
                {
                    db.superheroes.Add(superhero);
                    db.SaveChanges();
                    return RedirectToAction("Index");
                }
            }
            catch
            {
                ModelState.AddModelError("", "Unable to save changes.");
            }
            return View(superhero);
        }
        public ActionResult Create()
        {
            return View();
        }
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit(Superhero superhero)
        {

            var superheroToUpdate = db.superheroes.Find(superhero.Id);
            superheroToUpdate.SuperHeroName = superhero.SuperHeroName;
            superheroToUpdate.AlterEgoName = superhero.AlterEgoName;
            superheroToUpdate.PrimaryAbility = superhero.PrimaryAbility;
            superheroToUpdate.SecondaryAbility = superhero.SecondaryAbility;
            superheroToUpdate.CatchPhrase = superhero.CatchPhrase;
            if (TryUpdateModel(superheroToUpdate, "", new string[] { "SuperHeroName, AlterEgoName, PrimaryAbility, SecondaryAbility, CatchPhrase" }))
            {

                try
                {
                    db.SaveChanges();
                    return RedirectToAction("Index");

                }
                catch
                {
                    ModelState.AddModelError("", "Unable to save changes.");
                }
            }
            return RedirectToAction("Index");
        }
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Superhero superhero = db.superheroes.Find(id);
            if (superhero == null)
            {
                return HttpNotFound();
            }
            return View(superhero);
        }
        public ActionResult Delete(int? id, bool? saveChangesError=false)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            if (saveChangesError.GetValueOrDefault())
            {
                ViewBag.ErrorMessage = "Delete failed.";
            }
            Superhero superhero = db.superheroes.Find(id);
            if (superhero == null)
            {
                return HttpNotFound();
            }
            return View(superhero);

        }
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Delete(int id)
        {
            try
            {
                Superhero superhero = db.superheroes.Find(id);
                db.superheroes.Remove(superhero);
                db.SaveChanges();
            }
            catch
            {
                return RedirectToAction("Delete");
            }
            return RedirectToAction("Index");
        }
            
    }
}

SuperHeroProject/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - Superhero App Project</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")

</head>
<body>
    <div class="navbar navbar-fixed-top navbar-light" style="background-color: #e3f2fd; font-family: Jazz LET; font-style: oblique;">
        <div class="container-fluid">
            <div class="navbar-brand">
                <button type="button" class="float-xl-right  navbar-toggler" data-toggle="collapse" data-target="#navbarNav">
                    <span class="navbar-toggler-icon"></span>
                   
                </button>
                @Html.ActionLink("SuperHeroProject", "Index", "Superheroes", new { area = "" }, new { @class = "navbar-brand" })
            </div>
            <div class="navbar-collapse collapse" id="navbarNav">
                <ul class="navbar-nav mr-auto m-lg-2 mt-lg-0">
                    <li class="nav-item active" >@Html.ActionLink("Home", "Index", "Superheroes")</li>
                    <li class="nav-item active">@Html.ActionLink("About", "About", "Home")</li>
                    <li class="nav-item active">@Html.ActionLink("Contact", "Contact", "Home")</li>
                </ul>
                @Html.Partial("_LoginPartial")
            </div>
        </div>
    </div>
    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year - Superhero Collection App</p>
        </footer>
    </div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</body>
</html>